# Import libraries

In [1]:
import numpy as np
import pandas as pd
from myToolBox import create_stat_df, get_attributes_type, count_isolated, count_distinct

# Dataset-1

In [2]:
dataset_folder = 'dataset-1/'
dataset_path = dataset_folder + 'load.data'
attributes_path = dataset_folder + 'attributes.txt'

# Get all the attributes
attributes_type = get_attributes_type(attributes_path)

data = pd.read_csv(dataset_path,header=None, names=list(attributes_type.keys()))
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [3]:
create_stat_df(data, attributes_type).head(10)

          thuộc tính kiểu dữ liệu  tb/số pbiet  phg sai/số duy 1  số null
0          symboling      nominal     6.000000          0.000000        0
1  normalized-losses    numerical   122.000000         35.333947       41
2               make      nominal    22.000000          1.000000        0
3          fuel-type      nominal     2.000000          0.000000        0
4         aspiration      nominal     2.000000          0.000000        0
5       num-of-doors      nominal     2.000000          0.000000        2
6         body-style      nominal     5.000000          0.000000        0
7       drive-wheels      nominal     3.000000          0.000000        0
8    engine-location      nominal     2.000000          0.000000        0
9         wheel-base    numerical    98.756585          6.007070        0