# Import libraries

In [3]:
import numpy as np
import pandas as pd
from myToolBox import *

# Dataset-1

In [3]:
# Edit number in head() to show more or less
dataset_folder = 'dataset-1/'
create_stat_df(dataset_folder)

,Attribute,Data type,Mean/Distinct values,Std/Isolated values,Num of Nulls
0,symboling,nominal,6,0,0 (0.00%)
1,normalized-losses,numerical,122.00,35.33,41 (20.00%)
2,make,nominal,22,1,0 (0.00%)
3,fuel-type,nominal,2,0,0 (0.00%)
4,aspiration,nominal,2,0,0 (0.00%)
5,num-of-doors,nominal,2,0,2 (0.98%)
6,body-style,nominal,5,0,0 (0.00%)
7,drive-wheels,nominal,3,0,0 (0.00%)
8,engine-location,nominal,2,0,0 (0.00%)
9,wheel-base,numerical,98.76,6.01,0 (0.00%)
10,length,numerical,174.05,12.31,0 (0.00%)
11,width,numerical,65.91,2.14,0 (0.00%)
12,height,numerical,53.72,2.44,0 (0.00%)
13,curb-weight,numerical,2555.57,519.41,0 (0.00%)
14,engine-type,nominal,7,1,0 (0.00%)
15,num-of-cylinders,nominal,7,2,0 (0.00%)
16,engine-size,numerical,126.91,41.54,0 (0.00%)
17,fuel-system,nominal,8,2,0 (0.00%)
18,bore,numerical,3.33,0.27,4 (1.95%)
19,stroke,numerical,3.26,0.32,4 (1.95%)
20,compression-ratio,numerical,10.14,3.96,0 (0.00%)
21,horsepower,numerical,104.26,39.62,2 (0.98%)
22,peak-rpm,numerical,5125.37,478.15,2 (0.98%)
23,city-mpg,numerical,25.22,6.53,0 (0.00%)
24,highway-mpg,numerical,30.75,6.87,0 (0.00%)
25,price,numerical,13207.13,7927.27,4 (1.95%)

In [4]:
fill_missing_df(dataset_folder)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [4]:
dataset_folder = 'dataset-1/'

dataset_path = dataset_folder + 'load.data'
attributes_path = dataset_folder + 'attributes.txt'
attributes_type = get_attributes_type(attributes_path)
df = pd.read_csv(dataset_path,header=None, names=list(attributes_type.keys()))
attributes_type

hey line 1!

{'symboling': 'cat',
 'normalized-losses': 'cat',
 'make': 'cat',
 'fuel-type': 'cat',
 'aspiration': 'cat',
 'num-of-doors': 'cat',
 'body-style': 'cat',
 'drive-wheels': 'cat',
 'engine-location': 'cat',
 'wheel-base': 'cat',
 'length': 'cat',
 'width': 'cat',
 'height': 'cat',
 'curb-weight': 'cat',
 'engine-type': 'cat',
 'num-of-cylinders': 'cat',
 'engine-size': 'cat',
 'fuel-system': 'cat',
 'bore': 'cat',
 'stroke': 'cat',
 'compression-ratio': 'cat',
 'horsepower': 'cat',
 'peak-rpm': 'cat',
 'city-mpg': 'cat',
 'highway-mpg': 'cat',
 'price': 'cat'}

# Dataset 2

In [5]:
dataset_folder = 'dataset-2/'
dataset_path = dataset_folder + 'load.data'
attributes_path = dataset_folder + 'attributes.txt'

# Get all the attributes
attributes_type = get_attributes_type(attributes_path)

data = pd.read_csv(dataset_path,header=None, names=list(attributes_type.keys()))

In [9]:
# Edit number in head() to show more or less
create_stat_df(dataset_folder)
fill_missing_df(dataset_folder)

,timestamp,cylinder-number,customer,job-number,grain-screened,ink-color,proof-on-ctd-ink,blade-mfg,cylinder-division,paper-type,...,solvent-pct,ESA-Voltage,ESA-Amperage,wax,hardener,roller-durometer,current-density,anode-space-ratio,chrome-content,band-type
0,19910108,X126,TVGUIDE,25503,YES,KEY,YES,BENTON,GALLATIN,UNCOATED,...,36.4,0,0,2.5,1,34,40,105,100,band
1,19910109,X266,TVGUIDE,25503,YES,KEY,YES,BENTON,GALLATIN,UNCOATED,...,38.5,0,0,2.5,0.7,34,40,105,100,noband
2,19910104,B7,MODMAT,47201,YES,KEY,YES,BENTON,GALLATIN,UNCOATED,...,39.8,0,0,2.8,0.9,40,40,103.87,100,noband
3,19910104,T133,MASSEY,39039,YES,KEY,YES,BENTON,GALLATIN,UNCOATED,...,38.8,0,0,2.5,1.3,40,40,108.06,100,noband
4,19910111,J34,KMART,37351,NO,KEY,YES,BENTON,GALLATIN,UNCOATED,...,42.5,5,0,2.3,0.6,35,40,106.67,100,noband
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536,19941005,aa66,kmart,85813,NO,key,YES,BENTON,gallatin,super,...,38.5676,1.31936,0.0381443,1,1,34.7753,40,112.5,100,band
537,19941009,j44,best,38064,NO,key,YES,BENTON,gallatin,super,...,38.5676,1.31936,0.0381443,0,0,34.7753,40,110,100,band
538,19941009,aa58,kmart,85814,NO,key,YES,BENTON,gallatin,super,...,38.5676,1.31936,0.0381443,2.7,2.8,34.7753,40,108,100,band
539,19941010,aa70,kmart,85814,NO,key,YES,BENTON,gallatin,super,...,38.5676,1.31936,0.0381443,1.5,2.3,34.7753,40,108,100,band
540,19941010,j70,best,38064,NO,key,YES,BENTON,gallatin,super,...,38.5676,1.31936,0.0381443,2.5,1,34.7753,40,108.1,100,band

# Dataset 3

In [34]:
dataset_folder = 'dataset-3/'
dataset_path = dataset_folder + 'load.data'
attributes_path = dataset_folder + 'attributes.txt'

# Get all the attributes
attributes_type = get_attributes_type(attributes_path,
                                      numeric_term='numerical')

data = pd.read_csv(dataset_path,header=None, names=list(attributes_type.keys()))
data

TypeError: get_attributes_type() got an unexpected keyword argument 'numeric_term'

In [31]:
# Edit number in head() to show more or less
def summary_option(dataset_folder,output,input):
    summary_file = dataset_folder + 'summary.txt'
    stats,len_df = create_stat_df(dataset_folder)
    with open(summary_file,'w') as f:
        f.write('# So mau: {}\n\n'.format(len_df))
        f.write('# So thuoc tinh: {}\n\n'.format(len(stats)))
        for i in range(len(stats)):
            line_data = stats.iloc[i] # data of i-th row
            attri_name = line_data['Attribute']
            attri_type = line_data['Data type']
            f.write('# thuoc tinh {}: "{}" {}\n'.format(i+1,attri_name,attri_type))
    print('Option executed: "summary"')
    print('- summary log file: '+ summary_file)
    return summary_file

In [5]:
dataset_folder = 'dataset-3/'

In [8]:
def replace_option(dataset_folder,output_path,log_path):
    stats,len_df = create_stat_df(dataset_folder)
    df,filling_log = fill_missing_df(dataset_folder)
    with open(log_path,'w') as f:
        # For i in numbers of attribute
        for i in range(len(stats)):
            line_data = stats.iloc[i] # data of i-th row
            attri_name = line_data["Attribute"]
            attri_replace = filling_log[i]
            attri_null = line_data['Num of Nulls'].split(' ')[0]
            f.write('# thuoc tinh {}: "{}", {}, {}\n'.format(i+1,attri_name,attri_null,attri_replace))
    df.to_csv(output_path)
    print('Option executed: "summary"')
    print('- output file: ' + output_path)
    print('- summary log file: '+ log_path)
    return output_path,log_path
replace_option(dataset_folder,'output_path.csv','log.txt')

Option executed: "summary"
- output file: output_path.csv
- summary log file: log.txt

('output_path.csv', 'log.txt')

In [36]:
stats,len_df = create_stat_df(dataset_folder)
stats

,Attribute,Data type,Mean/Distinct values,Std/Isolated values,Num of Nulls
0,Sample-code-number,nominal,645,599,0 (0.00%)
1,Clump-Thickness,numerical,4.42,2.81,0 (0.00%)
2,Uniformity-of-Cell-Size,numerical,3.13,3.05,0 (0.00%)
3,Uniformity-of-Cell-Shape,numerical,3.21,2.97,0 (0.00%)
4,Marginal-Adhesion,numerical,2.81,2.85,0 (0.00%)
5,Single-Epithelial-Cell-Size,numerical,3.22,2.21,0 (0.00%)
6,Bare-Nuclei,numerical,3.54,3.64,16 (2.29%)
7,Bland-Chromatin,numerical,3.44,2.44,0 (0.00%)
8,Normal-Nucleoli,numerical,2.87,3.05,0 (0.00%)
9,Mitoses,numerical,1.59,1.71,0 (0.00%)
10,Class,nominal,2,0,0 (0.00%)

In [10]:

def normalizer(dataset_folder, mode = 'minmax'):
     
    # Load data 
    dataset_path = dataset_folder + 'load.data'
    attributes_path = dataset_folder + 'attributes.txt'
    attributes_type = get_attributes_type(attributes_path)
    df = pd.read_csv(dataset_path,header=None, names=list(attributes_type.keys()))
    
    filling_log = []
    # Get the mode (most appeared words in the list)
    def most_common(lst):
        return max(set(lst), key=lst.count)
        
    for item in df.keys():
        attribute_type = attributes_type[item]
        
        Series = df[item].tolist()

        if attribute_type == "num":
            Series = numericize_list(Series)
            mean_Series = "%.2f" % np.mean(Series)
            df[item] = df[item].replace("?",mean_Series)
            filling_log.append(mean_Series)
            
        if attribute_type == "cat":

            mode_Series = most_common(Series)
            df[item] = df[item].replace("?",mode_Series)
            filling_log.append(mode_Series)
    return df,filling_log

In [2]:
dataset_folder = 'dataset-3/'

In [5]:
Norm = Normalizer(mode='zscore')
df, log = Norm.fit_transform(dataset_folder)
df.head()

,Sample-code-number,Clump-Thickness,Uniformity-of-Cell-Size,Uniformity-of-Cell-Shape,Marginal-Adhesion,Single-Epithelial-Cell-Size,Bare-Nuclei,Bland-Chromatin,Normal-Nucleoli,Mitoses,Class
0,1000025,0.206936,-0.699995,-0.743299,-0.633247,-0.549561,-0.706962,-0.179662,-0.611825,-0.343912,2
1,1002945,0.206936,0.283845,0.266875,0.768621,1.710106,1.793542,-0.179662,-0.284112,-0.343912,2
2,1015425,-0.503866,-0.699995,-0.743299,-0.633247,-0.549561,-0.429128,-0.179662,-0.611825,-0.343912,2
3,1016277,0.562336,1.595632,1.613773,-0.633247,-0.097628,0.126540,-0.179662,1.354454,-0.343912,2
4,1017023,-0.148465,-0.699995,-0.743299,0.067687,-0.549561,-0.706962,-0.179662,-0.611825,-0.343912,2

In [34]:
class Normalizer:
    def __init__(self,mode,new_min=0,new_max=1):
        self.mode = mode
        self.new_min = new_min
        self.new_max = new_max 
        self.min_max_dict = {} # Dictionary mapping from attributes name to a tuple of (min,max)
        self.z_score_dict = {} # Dictionary mapping from attributes name to a tuple of (mean,std)
        self.transform_log = {} # Dictionary mapping from attributes name to a tuple of (min_log,max_log)
        
    def transform_minmax_Series(self,Series,min_max):
        # Retrieve min max from tuple
        min,max = min_max
        
        # Convert to float in case of strings
        Series = Series.astype(float)
        
        # Transform the Series to min max values 
        Series = (Series - min)/(max-min)*(self.new_max-self.new_min)+self.new_min
        
        return Series.round(2) # round to precision of 2 
    
    def transform_zscore_Series(self,Series,mean_std):
        # Retrieve mean, std from tuple
        mean,std = mean_std
        
        # Convert to float in case of strings
        Series = Series.astype(float)
        
        # Transform the Series to min max values 
        Series = ((Series - mean)/std).round(2)
        
        # Series_transform_log monitors the range of normalization within an attribute
        Series_transform_log = (np.min(Series),np.max(Series))
        return Series,Series_transform_log
        
        
    
    def fit_transform(self,dataset_folder):
        
        # Load data 
        df,_ = fill_missing_df(dataset_folder) # Fill missing value
        attributes_path = dataset_folder + 'attributes.txt'
        attributes_type = get_attributes_type(attributes_path)
        
        # Min-max 
        if self.mode == 'minmax':
            # Fitting min max of each attribute to the Normalize
            for item in df.keys():
                if attributes_type[item] == 'cat':
                    continue

                if attributes_type[item] == 'num':
                    attri_min = float(np.min(df[item]))
                    attri_max = float(np.max(df[item]))
                    self.min_max_dict[item] = (attri_min,attri_max)

            # Transform the dataframe
            for item in df.keys():
                if attributes_type[item] == 'cat':
                    continue

                if attributes_type[item] == 'num':
                    # Replace Series values with new normalized values with the scaler
                    df[item] = self.transform_minmax_Series(df[item], self.min_max_dict[item])
                    self.transform_log[item] = (self.new_min,self.new_max)
            
            return df,self.transform_log
        
        # Z-Score
        elif self.mode == 'zscore':
            # Fitting min max of each attribute to the Normalize
            for item in df.keys():
                if attributes_type[item] == 'cat':
                    continue

                if attributes_type[item] == 'num':
                    attri_items = df[item].astype(float)
                    attri_mean =  np.mean(attri_items)
                
                    attri_std =  np.std(attri_items)
                    self.z_score_dict[item] = (attri_mean,attri_std)
                    
            # Transform the dataframe
            for item in df.keys():
                if attributes_type[item] == 'cat':
                    continue

                if attributes_type[item] == 'num':
                    # Replace Series values with new normalized values with the scaler
                    df[item],transform_log = self.transform_zscore_Series(df[item], self.z_score_dict[item])
                    self.transform_log[item]= transform_log
            
            return df,self.transform_log
def normalize_option(dataset_folder,output_path,log_path):
    #stats,len_df = create_stat_df(dataset_folder)
    
    # Choose normalization mode
    print('Enter normalization mode: "minmax" or "zscore"?')
    normalizer_mode = input()
    
    # df and normalization log placeholder
    df = None
    norm_log = None

    # If option == minmax
    if normalizer_mode == "minmax":
        # User input for min max
        print("Enter new min:")
        new_min = float(input())
        new_max = float(input())
        
        # Declare normalizer
        Norm = Normalizer(mode = "minmax",new_min=new_min,new_max=new_max)
        df,norm_log = Norm.fit_transform(dataset_folder)
        
    # If options == zscore
    elif normalizer_mode == "zscore":
        # Declare normalizer
        Norm = Normalizer(mode = "zscore")
        df,norm_log = Norm.fit_transform(dataset_folder)
    
    with open(log_path,'w') as f:
        # For i in numbers of attribute
        for i,item in enumerate(norm_log.items()):
            attri_name = item[0]
            attri_range = item[1]
            f.write('# thuoc tinh {}: "{}", ({},{})\n'.format(i+1,attri_name,attri_range[0],attri_range[1]))
    df.to_csv(output_path)
    print('Option executed: "normalization"')
    print('- output file: ' + output_path)
    print('- summary log file: '+ log_path)
    return output_path,log_path

In [35]:
dataset_folder = 'dataset-2/'
normalize_option(dataset_folder,'test_output.csv','test_log.txt')

Enter normalization mode: "minmax" or "zscore"?
zscore
Option executed: "normalization"
- output file: test_output.csv
- summary log file: test_log.txt

('test_output.csv', 'test_log.txt')

In [31]:
df,_ = fill_missing_df(dataset_folder)

In [164]:
class Discretizer:
    def __init__(self,mode,depth=4,width=4):
        self.mode = mode
        self.depth = depth
        self.width = width
        self.attri_to_bins = {} # A dict map from attri to bin
        
    def fit_transform(self,dataset_folder):
        # Load data 
        df,_ = Normalizer(mode="minmax").fit_transform(dataset_folder)# Normalize before binning
        attributes_path = dataset_folder + 'attributes.txt'
        attributes_type = get_attributes_type(attributes_path)
 
        # Fit to data to create bins
        if self.mode == 'width':
            for item in df.keys():
                if attributes_type[item] == 'num':
                   
                    Series = df[item]
                    print(item)
                    bins = self.width_discretize(Series,width = self.width)
                    print(bins)
                    self.attri_to_bins[item] = bins
                else: continue
        elif self.mode == 'depth':
            for item in df.keys():
                if attributes_type[item] == 'num':
                    Series = df[item]
                    bins = self.depth_discretize(Series,depth = self.depth)
                    self.attri_to_bins[item] = bins
                else: continue
            
    def width_discretize(self,Series,width):
        '''
        Input: a Series and width of discretization
        Output: list of bins
        '''
        sorted_list = sorted(Series.astype(float).tolist())
        left_bound = np.min(sorted_list)
        right_bound = np.max(sorted_list)

        bins = []

        pivot = 0
        while pivot < right_bound:

            if pivot + width > right_bound:
                # Round to work with numerical error
                bins.append((np.round(pivot,2),right_bound)) #
                break

            # Round to work with numerical error
            bins.append((np.round(pivot,2),np.round(pivot+width,2))) 
            pivot += np.round(width,2)
        return bins

    def depth_discretize(self,Series,depth):
        '''
        Input: a Series and width of discretization
        Output: list of bins
        '''
        sorted_list = sorted(Series.astype(float).tolist())

        left_bound = 0
        right_bound = len(sorted_list)

        bins = []

        pivot = 0
        while pivot < right_bound:
            left_bin = sorted_list[pivot]

            if pivot + depth >= right_bound:
                # Round to work with numerical error
                right_bin = sorted_list[right_bound-1]
                bins.append((left_bin,right_bin))
                break

            # Round to work with numerical error
            right_bin = sorted_list[pivot+depth]
            bins.append((left_bin,right_bin)) 
            pivot += depth
        return bins

In [165]:
def val_in_bin(value,bin,mode):
    '''
    Input: value & bin (tuple of left bound and right bound)
    Output: True or False if value in that bin
    '''
    left_bound, right_bound = bin
    if mode == 'leftest': 
        return (value < right_bound and value >= left_bound)
    if mode == 'mid':
        return (value < right_bound and value >= left_bound)
    if mode == 'rightest':
        return (value <= right_bound and value >= left_bound)

def val_to_bin(value,bins):
    '''
    Input: value & sorted list of bins (bins are tuple of left bound and right bound)
    Output: bin that value falls in (the leftest bin)
    '''
    for i,bin in enumerate(bins):
        if i == 0:
            
            if val_in_bin(value,bin,mode="leftest"):
                return bin
            else: continue
        elif i == len(bins)-1:
           
            if val_in_bin(value,bin,mode="rightest"):
                return bin
            else: continue
        elif val_in_bin(value,bin,mode="mid"):
            return bin
        else: continue

In [166]:
Series = pd.Series([1,4,6,7,7,8,9])
bins = width_discretize(Series,width=2)
val_to_bin(0,bins)

(0, 2)

In [167]:
dataset_folder = 'dataset-3/'
D_obj = Discretizer(mode='width',width=0.1)
D_obj.fit_transform(dataset_folder)

Clump-Thickness
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]
Uniformity-of-Cell-Size
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]
Uniformity-of-Cell-Shape
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]
Marginal-Adhesion
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]
Single-Epithelial-Cell-Size
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]
Bare-Nuclei
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.1), (1.1, 1.12)]
Bland-Chromatin
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]
Normal-Nucleoli
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]
Mitoses
[(0, 0.1), (0.1, 0.2), (0.2, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 0.8), (0.8, 0.9), (0.9, 1.0), (1.0, 1.0)]

In [168]:
D_obj.attri_to_bins

{'Clump-Thickness': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)],
 'Uniformity-of-Cell-Size': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)],
 'Uniformity-of-Cell-Shape': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)],
 'Marginal-Adhesion': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)],
 'Single-Epithelial-Cell-Size': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)],
 'Bare-Nuclei': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.1),
  (1.1, 1.12)],
 'Bland-Chromatin': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)],
 'Normal-Nucleoli': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)],
 'Mitoses': [(0, 0.1),
  (0.1, 0.2),
  (0.2, 0.3),
  (0.3, 0.4),
  (0.4, 0.5),
  (0.5, 0.6),
  (0.6, 0.7),
  (0.7, 0.8),
  (0.8, 0.9),
  (0.9, 1.0),
  (1.0, 1.0)]}

In [112]:
val_to_bin(8,bins)

left
right

(8.0, 9.0)

In [116]:
val_in_bin(8,(1,6),mode="right")